### ISSUE TITLE
Amazing job!

### ISSUE THREAD

**Issue by seel-channel** [aasimsani/artificial_manga_panel_dataset#1]
Hello! I'm Felipe. 

Do you have a pretrained IA for [Object Detection for Comics using Manga109 Annotations](https://arxiv.org/pdf/1803.08670.pdf)?
I read README.md and you used this paper to benchmark your dataset. 

I want to create a autogenerated videos from Manga or Manhwa (get panels, show panels instead whole page, get text of bubbles speech, create narrations, add sfx, etc.). The idea, you will input manga's page and it will return a video

Disclaimer: I don't too much about IA. I'm a frontend developer and its my first time at IA

Conclusion: If you don't have a pretrained or source code for implementation, would you like to give me an idea to start build my own?

**Comment by seel-channel** [comment]
I found your ML project in [AMPD ML](https://github.com/aasimsani/ampd-ml)

**Comment by aasimsani** [comment]
Hi Felipe,

I do not have the trained model since I was not able to get access to that dataset. A very interesting idea and I think if you ask the Tokyo University lab for it they might oblige.

Here's my code for my model trained on this dataset: https://github.com/aasimsani/ampd-ml

It's not as good as I'd like but it is reasonable.

**Comment by seel-channel** [comment]
I forked this repository and I'm improving the dataset. Probably these days, I will do a pull request and upload a artificial manga dataset. 

I was thinking and the best solution for me. It's build my own IA (I always want to build a model and its the perfect time to do it)

I will share you my milestones
